name: PrintTalkJ Snapshot

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'maven'

      - name: Maven Deploy
        run: mvn -Dmaven.javadoc.failOnError=false clean verify
